import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

class ExportService {
  static Future<void> exportLeaderboard({
    required String monthYear,
    required List<Map<String, dynamic>> players,
  }) async {
    final pdf = pw.Document();
    final String title = monthYear == 'Overall' ? 'OVERALL LEADERBOARD' : '${monthYear.toUpperCase()} LEADERBOARD';

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('BALL KILLER CLUB', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                    pw.Text(DateFormat('dd/MM/yyyy').format(DateTime.now())),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Center(
                child: pw.Text(title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.orange)),
              ),
              pw.SizedBox(height: 20),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('RANK', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('PLAYER NAME', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                      pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('BALLS LOST', style: pw.TextStyle(fontWeight: pw.FontWeight.bold))),
                    ],
                  ),
                  ...players.asMap().entries.map((entry) {
                    final index = entry.key;
                    final p = entry.value;
                    return pw.TableRow(
                      children: [
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${index + 1}')),
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(p['name'].toString().toUpperCase())),
                        pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(p['total'].toString())),
                      ],
                    );
                  }).toList(),
                ],
              ),
              pw.SizedBox(height: 40),
              pw.Footer(
                trailing: pw.Text('Generated by Ball Killer App', style: const pw.TextStyle(color: PdfColors.grey)),
              ),
            ],
          );
        },
      ),
    );

    await _saveAndShare(pdf, 'leaderboard_${monthYear.replaceAll('-', '_')}.pdf');
  }

  static Future<void> exportFineReport({
    required String monthYear,
    required List<Map<String, dynamic>> sortedPlayers,
  }) async {
    final pdf = pw.Document();
    final topPlayer = sortedPlayers.isNotEmpty ? sortedPlayers.first : null;
    final int fineAmount = topPlayer != null ? (topPlayer['total'] as int) * 50 : 0;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Text('CLUB FINE REPORT - $monthYear', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
              ),
              pw.SizedBox(height: 30),
              if (topPlayer != null && (topPlayer['total'] as int) > 0) ...[
                pw.Container(
                  padding: const pw.EdgeInsets.all(20),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.red, width: 2),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(10)),
                  ),
                  child: pw.Column(
                    children: [
                      pw.Text('TOP BALL KILLER NOTICE', style: pw.TextStyle(fontSize: 16, color: PdfColors.red, fontWeight: pw.FontWeight.bold)),
                      pw.SizedBox(height: 10),
                      pw.Text('NAME: ${topPlayer['name'].toString().toUpperCase()}', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
                      pw.Text('BALLS LOST: ${topPlayer['total']}', style: pw.TextStyle(fontSize: 16)),
                      pw.Divider(color: PdfColors.grey),
                      pw.Text('TOTAL FINE: $fineAmount BDT', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.red)),
                    ],
                  ),
                ),
              ],
              pw.SizedBox(height: 30),
              pw.Text('Full Ranking:', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey300),
                children: [
                  pw.TableRow(
                    decoration: const pw.BoxDecoration(color: PdfColors.grey100),
                    children: [
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('No.')),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Name')),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Lost')),
                      pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('Fine (50/ball)')),
                    ],
                  ),
                  ...sortedPlayers.asMap().entries.map((entry) {
                    final i = entry.key;
                    final p = entry.value;
                    final lost = p['total'] as int;
                    return pw.TableRow(
                      children: [
                        pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('${i + 1}')),
                        pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(p['name'].toString().toUpperCase())),
                        pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text('$lost')),
                        pw.Padding(padding: const pw.EdgeInsets.all(5), child: pw.Text(i == 0 ? '${lost * 50} BDT' : '-')),
                      ],
                    );
                  }).toList(),
                ],
              ),
              pw.SizedBox(height: 50),
              pw.Text('Note: Fines must be paid to the club treasurer.', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await _saveAndShare(pdf, 'fine_report_$monthYear.pdf');
  }

  static Future<void> _saveAndShare(pw.Document pdf, String fileName) async {
    final output = await getTemporaryDirectory();
    final file = File("${output.path}/$fileName");
    await file.writeAsBytes(await pdf.save());
    await Share.shareXFiles([XFile(file.path)], text: 'Ball Killer Club Report');
  }
}
